FROM node:22-bullseye AS builder
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm ci

# Copier le code
COPY . .

# Builder le projet Next.js
RUN npm run build

# Image finale légère
FROM node:22-bullseye
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app ./
EXPOSE 4002

CMD ["npm", "start"]