services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: gvs3d
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
    
