# ==========================================
# Stage 1 : builder
# ==========================================
FROM node:25.2.1-bookworm-slim AS builder

WORKDIR /app

# Installer toutes les dépendances (y compris devDependencies pour le build)
COPY package*.json ./
RUN npm ci

# Copier tout le projet 
COPY . .

# Build NextJS
RUN npm run build

# ==========================================
# Stage 2 : runner
# ==========================================
FROM node:25.2.1-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production
ENV NODE_OPTIONS="--max-old-space-size=512"
ENV NEXT_TELEMETRY_DISABLED=1

# Installer uniquement les dépendances de production
COPY package*.json ./
RUN npm ci --omit=dev

# Récupérer uniquement les artéfacts du build
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# Mode rootless (création propre de l'utilisateur)
RUN groupadd -g 1002 nodejs && \
    useradd -u 1002 -g nodejs -s /bin/sh gvs3d

# Donner la propriété des fichiers à l'utilisateur non-root
RUN chown -R gvs3d:nodejs /app

# Basculer sur l'utilisateur sécurisé
USER gvs3d

EXPOSE 4002

CMD ["npm", "start"]